os:
  - linux
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6
      - fonts-droid-fallback
      - libsecret-1-dev
      - libstdc++6
      - gcc-4.8
      - g++-4.8
      - gcc-4.8-multilib
      - g++-4.8-multilib
git:
  depth: 3
env:
  - FLUTTER_VERSION=stable
  - FLUTTER_VERSION=dev
matrix:
  allow_failures:
    - env: FLUTTER_VERSION=dev
before_script:
  - git clone https://github.com/flutter/flutter.git -b $FLUTTER_VERSION
  - ./flutter/bin/flutter doctor
  - chmod +x travis_script.sh
script:
  # - ./travis_script.sh
  # - ./flutter/bin/flutter analyze
  - ./flutter/bin/flutter test
cache:
  directories:
    - $HOME/shared/.pub-cache
